PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX pch: <https://purl.org/pch/>

SELECT ?patient ?disease ?diagnosisDate ?doctorNotes ?snomedConcept
WHERE {   
	?patient rdf:type pch:Patient .
	?patient pch:taxCode "RSSMR90H294N".
	?diagnosisDocument rdf:type pch:DiseaseDiagnosisDocument;
 		pch:refersToPatient ?patient ;
		pch:hasEmissionDate ?diagnosisDate ;   
		pch:has_disease ?disease.   
	OPTIONAL {?diagnosisDocument pch:hasDoctorNotes ?doctorNotes }. 
	OPTIONAL {?disease pch:refersToSnomedConcept ?snomedConcept }.
}
ORDER BY ?diagnosisDate
