PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX pch: <https://purl.org/pch/>

SELECT ?patient ?procedure ?procedureDate ?doctorNotes ?snomedConcept
WHERE {   
	?patient rdf:type pch:Patient .
	?patient pch:taxCode "RSSMR90H294N".
	?procedureDocument rdf:type pch:ProcedureExecutionDocument;
 		pch:refersToPatient ?patient ;
		pch:hasEmissionDate ?procedureDate ;   
		pch:has_procedure ?procedure .   
	OPTIONAL{?procedureDocument pch:hasDoctorNotes ?doctorNotes}.
        OPTIONAL{?procedure pch:refersToSnomedConcept ?snomedConcept}.

}
ORDER BY ?procedureDate

