PREFIX pch:<https://purl.org/pch/>

SELECT ?snomedConcept ?patient ?procedureDate ?doctorNotes
WHERE {
  ?procedureDocument rdf:type pch:ProcedureExecutionDocument .
  OPTIONAL {?procedureDocument pch:hasDoctorNotes ?doctorNotes}
  ?procedureDocument pch:has_procedure ?procedure .
  ?procedure pch:refersToSnomedConcept ?snomedConcept . 
  ?snomedConcept a <http://snomed.info/id/265702005>.
  ?procedureDocument pch:hasEmissionDate ?procedureDate.
  ?procedureDocument pch:refersToPatient ?patient
}

ORDER BY ?procedureDate

